export enum ACTIONS {
   UPDATE_MAP_FIELD = 'UPDATE_MAP_FIELD',
   DELETE_MAP_FIELD = 'DELETE_MAP_FIELD',
   CREATE_NPC_TEMPLATE = 'CREATE_NPC_TEMPLATE',
   ADD_NPC = 'ADD_NPC',
   DELETE_NPC = 'DELETE_NPC',
   CREATE_ITEM_TEMPLATE = 'CREATE_ITEM_TEMPLATE',
}
