export enum EngineEvents {
   CreateNewPlayer = 'CreateNewPlayer',
   NewCharacterCreated = 'NewCharacterCreated',
   PlayerDisconnected = 'PlayerDisconnected',
   PlayerStartedMovement = 'PlayerStartedMovement',
   PlayerStopedMovementVector = 'PlayerStopedMovementVector',
   PlayerStopedAllMovementVectors = 'PlayerStopedAllMovementVectors',
   PlayerMoved = 'PlayerMoved',
   PlayerTriesToStartedMovement = 'PlayerTriesToStartedMovement',
   ProjectileCreated = 'ProjectileCreated',
   ProjectileMoved = 'ProjectileMoved',
   RemoveProjectile = 'RemoveProjectile',
   ProjectileRemoved = 'ProjectileRemoved',

   CharacterLostHp = 'CharacterLostHp',
   CharacterGotHp = 'CharacterGotHp',
   CharacterLostSpellPower = 'CharacterLostSpellPower',
   CharacterGotSpellPower = 'CharacterGotSpellPower',
   CharacterDied = 'CharacterDied',
   TakeCharacterHealthPoints = 'TakeCharacterHealthPoints',
   AddCharacterHealthPoints = 'AddCharacterHealthPoints',
   TakeCharacterSpellPower = 'TakeCharacterSpellPower',
   AddCharacterSpellPower = 'AddCharacterSpellPower',

   PlayerTriesToCastASpell = 'PlayerTriesToCastASpell',
   PlayerCastSpell = 'PlayerCastSpell',
   PlayerCastSubSpell = 'PlayerCastSubSpell',
   PlayerCastedSpell = 'PlayerCastedSpell',
   ApplyTargetSpellEffect = 'ApplyTargetSpellEffect',
   ApplyLocationSpellEffect = 'ApplyLocationSpellEffect',
   RemoveAreaSpellEffect = 'RemoveAreaSpellEffect',
   SpellChannelingFinished = 'SpellChannelingFinished',
   SpellChannelingInterrupted = 'SpellChannelingInterrupted',
   RemoveTickOverTimeEffect = 'TickOverTimeFinished',
}
