import { SpellType } from './SpellType';
import type { Spell } from './types/Spell';

export const ALL_SPELLS: Record<string, Spell> = {
   DirectHit: {
      type: SpellType.DIRECT_HIT,
      name: 'DirectHit',
      range: 400,
      speed: 4,
      damage: 25,
      cooldown: 1000,
      image: "../assets/spritesheets/spells/mage/fireball.jpg",
      description: "Inflicts 25 Fire damage to an enemy and causes them to burn for 8 sec.",
   },
   Projectile: {
      type: SpellType.PROJECTILE,
      name: 'Projectile',
      range: 4000,
      speed: 40,
      damage: 40,
      cooldown: 0,
      image: "../assets/spritesheets/spells/mage/fireball.jpg",
      description: "Inflicts 40 Fire damage to an enemy and causes them to burn for 8 sec.",
   },
   MonsterProjectile: {
      type: SpellType.PROJECTILE,
      name: 'MonsterProjectile',
      range: 1000,
      speed: 40,
      damage: 20,
      cooldown: 2000,
      image: "../assets/spritesheets/spells/mage/fireball.jpg",
      description: "Inflicts 20 Fire damage to an enemy and causes them to burn for 8 sec.",
   },
   MonsterInstant1: {
      type: SpellType.DIRECT_HIT,
      name: 'MonsterInstant1',
      range: 500,
      speed: 40,
      damage: 15,
      cooldown: 1000,
      image: "../assets/spritesheets/spells/mage/fireball.jpg",
      description: "Inflicts 15 Fire damage to an enemy and causes them to burn for 8 sec.",
   },
   MonsterInstant2: {
      type: SpellType.DIRECT_HIT,
      name: 'MonsterInstant2',
      range: 1500,
      speed: 40,
      damage: 1,
      cooldown: 1000,
      image: "../assets/spritesheets/spells/mage/fireball.jpg",
      description: "Inflicts 40 Fire damage to an enemy and causes them to burn for 8 sec.",
   },
   InstantProjectile: {
      type: SpellType.PROJECTILE,
      name: 'InstantProjectile',
      range: 1000,
      speed: 1000,
      damage: 69,
      cooldown: 0,
      image: "../assets/spritesheets/spells/mage/fireball.jpg",
      description: "Inflicts 69 Fire damage to an enemy and causes them to burn for 8 sec.",
   },
};
